version: "3"

services:
  gitlab:
    image: "twang2218/gitlab-ce-zh"
    container_name: "gitlab"
    #restart: always
    hostname: "192.168.1.134" #部署机器的ip,非容器ip(因为是本地不是线上所以用ip，线上的话可以用域名)
    environment:
      TZ: "Asia/Shanghai"
      GITLAB_OMNIBUS_CONFIG:  | 
        external_url 'http://192.168.1.134'  #使用这个地址访问gitlab web ui(因为是本地不是线上所以用ip，线上的话可以用域名)
        #gitlab_rails['gitlab_shell_ssh_port'] = 2222 #ssh clone代码地址
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        unicorn['port'] = 8888 #gitlab一个内部端口
    #privileged: true			#设置容器的权限为root
    ports:
      - "81:80" #web 80 端口
      #- '443:443'      #web 443 端口,本次未使用就不开放了
      - "2222:22" #ssh 检出代码 端口
    volumes:
      - ./etc:/etc/gitlab #Gitlab配置文件目录
      - ./data:/var/opt/gitlab #Gitlab数据目录
      - ./logs:/var/log/gitlab #Gitlab日志目录